version: '3.8'

services:
  go-app:
    container_name: go-crud-live
    build: .
    image: go-crud-live:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@go_db:5432/go_crud_live?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_crud_live
    ports:
      - "5433:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
